### ISSUE TITLE
blur does not hide the menu

### ISSUE THREAD

**Issue by vschoettke** [thebritican/elm-autocomplete#14]
In version 3.01 (with elm 0.17) the menu is not hidden if the focus is removed. Selecting an item still hides the menu so I guess the "onBlur" in the div is not working anymore.

**Comment by gregziegan** [comment]
Yes, this is an issue with the `virtualdom` Elm implementation. didn't realize it was a problem here as well as in #13. Thanks for letting me know!

**Comment by demsullivan** [comment]
I saw that this was resolved using an `onBlur` event, then subsequently changed to handle it a different way... though using 3.2.0 the menu isn't going away on blur for me.

**Comment by gregziegan** [comment]
@demsullivan thanks for the catch! I was manually testing and missed this! Solved Esc, but not blur. `3.2.1` should have the fix. `click` events fire after blur (on release of the mouse), `onMouseDown` will allow the input to still be filled in when selecting a menu item with the mouse.

This just means: time to write some tests! 😅
