### ISSUE TITLE
Allow fuzzy string matching

### ISSUE THREAD

**Issue by maximsch2** [thebritican/elm-autocomplete#24]
It would be great if autocomplete would allow fuzzy matching. 
It seems like it could be implemented using  elm-fuzzy. http://package.elm-lang.org/packages/tripokey/elm-fuzzy/5.0.1/Fuzzy

Are there any workaround right now to hook it up? Maybe some way to propose completion list based on current input?

**Comment by gregziegan** [comment]
See #26 for how I plan to do this! (Hint: I don't. But you will be able to without dealing with _my_ API 😄)

**Comment by maximsch2** [comment]
This sounds like a perfect plan!

**Comment by gregziegan** [comment]
Closing this since it's already possible with the unreleased 4.0
