### ISSUE TITLE
issue with matches

### ISSUE THREAD

**Issue by roine** [thebritican/elm-autocomplete#25]
Use case: I focus the input, select an item with the keyboard and press tab to select it.

Actual: the matches list shows all the items
Expected: the matches list should only show the item I selected while using tab

Maybe I'm misunderstanding how it should work, for me value should be whatever you type and matches should be what you selected in that case you could know whether you got a match or it was free text.

**Comment by gregziegan** [comment]
Hi! What browser & OS is this? I just tried highlighting different items via keyboard arrows and hovering with mouse and tab worked fine for me 🙂.

Tried this in Chrome, Firefox, and Safari (all Mac OSX).

This reminds me to do some browser testing!

**Comment by gregziegan** [comment]
This is most likely irrelevant with the new API, since it will be handled in your app's business logic.
