### ISSUE TITLE
New API: Control your own Items

### ISSUE THREAD

**Issue by gregziegan** [thebritican/elm-autocomplete#26]
After talking with smart folks at the SF Elm meetup a lot this past month, some key insights were gleaned about how to make this API better.

I'm moving this API to having a single source of truth: your app's model.

https://github.com/evancz/elm-sortable-table/#single-source-of-truth

I'll be working with Evan Czaplicki this week (via a video pairing session) to move the API forward.

Benefits include:
- Less configuration
- Complete freedom to manipulate the data you send autocomplete
- Use any data shape you want: does not need to be a `List String`, can be a `List a`
- Easily serializable
  - I was sinning before and keeping `Config` in my Model
- Less chances for `Autocomplete` to get out of sync with your app.

Get excited 🎉

**Comment by roine** [comment]
Awesome news @thebritican, I was looking for the data shape to accept more that just a string. Looking forward!

**Comment by gregziegan** [comment]
https://twitter.com/czaplic/status/761265397437833216

The video of how we developed the new (soon to be implemented) API ^^

**Comment by liamcurry** [comment]
Is there a branch/PR with the new WIP API?

**Comment by gregziegan** [comment]
A branch, yep. It'll be called `new-api` when I push it up soon. (Most likely tomorrow).

Not worthy of attention until I get it closer to compiling.

**Comment by gregziegan** [comment]
Just pushed the branch, it compiles!

Now it's time to clean up, document, and flesh out the examples

**Comment by gregziegan** [comment]
Closing this since the new API is pretty much done, waiting on whitelisting/new Elm release to publish a new version (4.0). You can follow the progress in #30
