### ISSUE TITLE
Used with multiple declarations Autocomplete breaks the Elm compiler and gives runtime errors

### ISSUE THREAD

**Issue by edmellum** [thebritican/elm-autocomplete#29]
I don't know if this belongs in elm-compiler or here. As I couldn't reproduce it without Autocomplete I decided this is where it should go first. To me the problem does however seem to be the compiler doing something it shouldn't.

Using [this example](https://gist.github.com/edmellum/f4ab2fc14f9344c3b7cf4969f3ede6ed) the ordering of the compiled Javascript in the `let` declaration in `update` becomes incorrect and causes `val` to become `undefined`. If one attempts to use `val` for anything a runtime exception is raised. I haven't been able to produce a reproduction without elm-autocomplete by just attempting to do the same things it does. Somehow it's causing the Elm compiler to mess up the order in `let` blocks.

**Comment by pdamoc** [comment]
Switching lines 22 and 23 from the gist ends up in a thrown runtime error.

**Comment by edmellum** [comment]
Closing this and opening an issue in elm-compiler as I've created a case without autocomplete.
