### ISSUE TITLE
Integer IDs

### ISSUE THREAD

**Issue by maximsch2** [thebritican/elm-autocomplete#35]
Current `toId` has to return a String. Is there any reason why that is the case instead of arbitrary `comparable`?

**Comment by gregziegan** [comment]
So that `Html.Keyed` has a `String` to identify nodes. I used `Keyed.ul` in `elm-autocomplete` so that node diff-ing is quicker.

I took inspiration from:
http://package.elm-lang.org/packages/evancz/elm-sortable-table/1.0.0/Table#config

**Comment by maximsch2** [comment]
Makes sense, thanks for explaining!
